Repository department-of-veterans-affairs/va-enp-api, pull requests merged in 2025-03, with the labels that each got.

#183 #125 Docker configuration changes
  .env.local
  .talismanrc
  app/main.py
  ci/.env.docker
  run_app_local.py
Labels: minor

#197 #135 - Implement RetryableError and NonRetryableError
  app/exceptions.py
  app/legacy/v2/notifications/utils.py
  app/providers/provider_aws.py
  app/providers/provider_base.py
  tests/app/legacy/v2/notifications/test_utils.py
  tests/app/providers/test_provider_aws.py
  tests/app/providers/test_provider_base.py
Labels: patch

#201 #200 - Removed ENP Database
  .talismanrc
  app/dao/__init__.py
  app/dao/notifications_dao.py
  app/db/__init__.py
  app/db/base.py
  app/db/db_init.py
  app/db/model_mixins.py
  app/db/models.py
  app/legacy/dao/notifications_dao.py
  app/legacy/dao/templates_dao.py
  app/legacy/v2/notifications/rest.py
  app/legacy/v2/notifications/utils.py
  app/main.py
  app/routers.py
  cd/dev.env
  cd/perf.env
  ci/.env.docker
  ci/docker-compose-local.yml
  postman/enp-api.postman_collection.json
  tests/app/db/test_db_init.py
  tests/app/db/test_models.py
  tests/app/legacy/v2/notifications/test_rest.py
  tests/app/legacy/v2/notifications/test_utils.py
Labels: patch

#202 HOTFIX - Update Dependencies
  .talismanrc
  poetry.lock
  pyproject.toml
  tests/app/providers/__init__.py
Labels: patch

#210 #175 - Ensure v2 and legacy/v2 error structure matches NAPI
  app/auth.py
  app/legacy/v2/notifications/rest.py
  app/legacy/v2/notifications/route_schema.py
  app/legacy/v2/notifications/utils.py
  app/routers.py
  tests/app/legacy/v2/notifications/test_rest.py
  tests/app/legacy/v2/notifications/test_route_schema.py
  tests/app/test_auth.py
Labels: major

#212 #187 - Fix secret json interpolation in deploy workflow
  .github/workflows/deploy.yml
Labels: patch
