Repository department-of-veterans-affairs/va-enp-api, pull requests merged in 2025-01, with the labels that each got.

#124 HOTFIX - Poetry Version Check
  pyproject.toml
  scripts/run_tests.sh
Labels: patch

#123 #67 - Eliminate leaked semaphores and ensure FastAPI lifespan cleanup code executes on app exit
  app/main.py
  tests/app/test_main.py
Labels: patch

#122 #96 Basic JWT Auth
  .talismanrc
  app/auth.py
  app/legacy/v2/notifications/rest.py
  app/main.py
  app/v3/__init__.py
  ci/.env.local
  poetry.lock
  pyproject.toml
  scripts/run_tests.sh
  tests/app/test_auth.py
  tests/conftest.py
Labels: minor

#109 #95 - year based partitioning notification table
  .talismanrc
  app/db/models.py
  app/main.py
  tests/app/db/test_models.py
Labels: major

#129 HOTFIX - Update Dependencies and Asyncio automode
  poetry.lock
  pyproject.toml
  tests/app/db/test_db_init.py
  tests/app/legacy/v2/notifications/test_rest.py
  tests/app/legacy/v2/notifications/test_utils.py
  tests/app/providers/test_provider_aws.py
  tests/app/providers/test_provider_base.py
  tests/app/test_main.py
Labels: patch

#141 #116 Notification routes with single handler
  app/legacy/v2/notifications/rest.py
  app/legacy/v2/notifications/route_schema.py
  app/main.py
  tests/app/legacy/v2/notifications/test_rest.py
Labels: minor

#146 #128 - Fix for Keyboard Interrupt Issue
  .github/pull_request_template.md
  app/legacy/v2/notifications/rest.py
  app/legacy/v2/notifications/route_schema.py
  app/main.py
  pyproject.toml
  tests/app/test_main.py
Labels: patch

#149 #75 - Add task definition with GHA to render definition and push env file
  .github/actions/ecs-task-render-deploy/action.yml
  .github/workflows/deploy.yml
  cd/dev.env
  cd/perf.env
  cd/va-enp-api-task-definition.json
Labels: minor

#151 HOTFIX - Update Tests
  tests/app/test_main.py
Labels: patch

#150 #76 - Implements deploy to environment workflow
  .github/actions/build-push-artifacts/action.yml
  .github/actions/ecs-task-render-deploy/action.yml
  .github/workflows/deploy.yml
  cd/va-enp-api-task-definition.json
  scripts/wait_for_it.sh
Labels: patch

#152 HOTFIX - Update Dependencies
  .pre-commit-config.yaml
  app/main.py
  poetry.lock
  tests/app/db/test_db_init.py
  tests/app/providers/__init__.py
  tests/app/providers/test_provider_aws.py
Labels: patch
